# Generated by Django 5.1.2 on 2024-10-19 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaucetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42)),
                ('ip_address', models.GenericIPAddressField()),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('wallet_address', 'ip_address', 'request_date')},
            },
        ),
    ]
