# Generated by Django 5.1.2 on 2024-10-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faucetrequest',
            old_name='request_date',
            new_name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='faucetrequest',
            unique_together=set(),
        ),
    ]
